language: android

android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
#    - extra

jdk:
  - oraclejdk8
   
install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'

notifications:
  email: false

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Turn off caching to avoid any caching problems
# cache: false

# Use the Travis Container-Based Infrastructure
sudo: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
